name: Firely.Terminal (GitHub Actions)
description: Run Firely.Terminal and the offical FHIR Java Validator in a GitHub Actions pipeline

inputs:
  PATH_TO_CONFORMANCE_RESOURCES:
    description: 'Relative paths of the folder(s) containing FHIR Conformance resources (StructureDefinition, ValueSet, CodeSystem)'
    required: true
  PATH_TO_EXAMPLES:
    description: 'Relative paths of the folder(s) containing examples for the FHIR Conformance resources defined by the project'
    required: false

# Validate all resources using Firely Terminal 
runs:
  using: "composite"
  shell: bash
  steps:
    # Test SDK version
    - name: Check .NET SDK Version
      run: |
        dotnet --version
          
    # Install Firely Terminal
    - name: Install Firely Terminal
      run: |
        dotnet tool install --global Firely.Terminal --version $FIRELY_TERMINAL_VERSION
      
    # Test Firely Terminal install
    - name: Check Firely Terminal Version
      run: |
        fhir -v
          
    # Add resources for validation to the stack
    # Examples need to go last otherwise we can't find the profiles used in the examples anymore on the stack when validating (the stack is FIFO)
    - name: Add resources to the Firely Terminal stack
      run: |
        for p in $INPUT_PATH_TO_CONFORMANCE_RESOURCES; 
        do 
          echo Accessing "$p" and pushing resources to the stack...
          if [ -d "$GITHUB_WORKSPACE/$p" ]; then
            cd $GITHUB_WORKSPACE/$p
            fhir push .
          else
            echo Cannot access "$p" as the path does not exist
          fi
        done
      
    # Restore all dependencies listed in the package.json file (need to be on the root level)
    - name: FHIR Dependency restore
      run: |
        fhir restore
    
    # Validate all conformance resources on the stack
    - name: Validate all conformance resources in scope of the repository
      run: | 
        while true; do
          currentResource=$(fhir peek)
          if [[ "$currentResource" == *"The stack is empty."* ]]; then
            echo "Validation was executed for all resources on the stack"
            break
          fi
          echo Validating $currentResource ...
            
          result=$(fhir validate)
          echo $result
          if [[ "$result" == *"INVALID"* ]]; then
            exit 1
          fi
            
          fhir pop > /dev/null
        done
      
     #Examples are currently not used as Firely Terminal can't validate against profiles on the stack right now
