name: Firely.Terminal (GitHub Actions)
description: Run Firely.Terminal and the offical FHIR Java Validator in a GitHub Actions pipeline

inputs:
  PATH_TO_CONFORMANCE_RESOURCES:
    description: 'Relative paths of the folder(s) containing FHIR Conformance resources (StructureDefinition, ValueSet, CodeSystem)'
    required: true
  PATH_TO_EXAMPLES:
    description: 'Relative paths of the folder(s) containing examples for the FHIR Conformance resources defined by the project'
    required: false

# Validate all resources using Firely Terminal 
runs:
  using: "composite"
  steps:
  
    # Firely.Terminal steps
    
    # Test Firely SDK version
    - name: Check .NET SDK Version
      run: |
        CHECK_DOTNET_VERSION=$(dotnet --version)
        echo "DOTNET_VERSION: $CHECK_DOTNET_VERSION"
      shell: bash
          
    # Install Firely.Terminal
    - name: Install Firely.Terminal
      run: |
        dotnet tool install --global Firely.Terminal --version $FIRELY_TERMINAL_VERSION > /dev/null
        echo "Successfully installed Firely.Terminal"
      shell: bash
      env:
       FIRELY_TERMINAL_VERSION: 2.0.0
      
    # Test Firely.Terminal install
    - name: Check Firely Terminal Version
      run: |
        CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ') # Print everything in a single line
        echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
      shell: bash
          
    # Add conformance resources for validation to the stack
    - name: Add resources to the Firely Terminal stack
      run: |
        echo "Trying to validate conformance resources located at the following relative path(s): $INPUT_PATH_TO_CONFORMANCE_RESOURCES"
        for p in $INPUT_PATH_TO_CONFORMANCE_RESOURCES; 
        do 
          echo Accessing "$p" and pushing resources to the stack...
          if [ -d "$GITHUB_WORKSPACE/$p" ]; then
            cd $GITHUB_WORKSPACE/$p
            fhir push .
          else
            echo Cannot access "$p" as the path does not exist
          fi
        done
      shell: bash
      env:
        INPUT_PATH_TO_CONFORMANCE_RESOURCES: ${{ inputs.PATH_TO_CONFORMANCE_RESOURCES }}
      
    # Restore all dependencies listed in the package.json file (need to be on the root level)
    - name: FHIR Dependency restore
      run: |
        FHIR_RESTORE=$(fhir restore | tr '\n' ' ')  # Print everything in a single line
        echo "Restore of package.json was successful: $FHIR_RESTORE"
      shell: bash
    
    # Validate all conformance resources on the stack
    - name: Validate all conformance resources in scope of the repository
      run: |
        count=0
        while true; do
          currentResource=$(fhir peek)
          if [[ "$currentResource" == *"The stack is empty."* ]]; then
            echo "Validation was executed for all conformance resources on the stack. Validated $count conformance resource(s)."
            break
          fi
          ((count=count+1))
          echo "Validating $currentResource ..."
            
          result=$(fhir validate)
          echo $result
          if [[ "$result" == *"INVALID"* ]]; then
            exit 1
          fi
            
          fhir pop > /dev/null
        done
      shell: bash
      
     #Examples are currently not used as Firely Terminal can't validate against profiles on the stack right now
     
         # Validate all conformance resources on the stack
    - name: Success (Firely.Terminal)
      run: |
        echo "Finished validation with Firely.Terminal"
      shell: bash
    
    # Offical HL7 Java validator steps
    
    - name: Download Java Validator
      run: | 
        wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/download/$JAVA_VALIDATOR_VERSION/validator_cli.jar
      shell: bash
      env:
       JAVA_VALIDATOR_VERSION: 5.3.8
      
    - name: Install jq
      run: | 
        sudo apt-get update > /dev/null
        sudo apt-get install --no-install-recommends -y jq findutils curl ca-certificates > /dev/null
      shell: bash
          
    - name: Validate all conformance resources in scope of the repository
      run: |
        IG_DEPENDENCIES=$(jq '.dependencies | to_entries | map("-ig " + .key + "#" + .value) | join(" ")' package.json)
        for p in $INPUT_PATH_TO_CONFORMANCE_RESOURCES; 
        do  
          UNESCPAED_IG_DEPENDENCIES=$(echo $IG_DEPENDENCIES | tr -d '"')
          java -jar validator_cli.jar $GITHUB_WORKSPACE/$p -version $FHIR_VERSION $UNESCPAED_IG_DEPENDENCIES
        done
      shell: bash
      env:
       FHIR_VERSION: "4.0"
       INPUT_PATH_TO_CONFORMANCE_RESOURCES: ${{ inputs.PATH_TO_CONFORMANCE_RESOURCES }}
        
    - name: Validate all example resources in scope of the repository
      run: |
        IG_DEPENDENCIES=$(jq '.dependencies | to_entries | map("-ig " + .key + "#" + .value) | join(" ")' package.json)
        for p in $INPUT_PATH_TO_CONFORMANCE_RESOURCES; # Get combined path to conformance resources, we want to validate against the current version of the conformance resources
        do  
          COMBINED_IG_PARAMETERS+="-ig $GITHUB_WORKSPACE/$p "
        done
          
        for p in $PATH_TO_EXAMPLES; 
        do  
          UNESCPAED_IG_DEPENDENCIES=$(echo $IG_DEPENDENCIES | tr -d '"')
          java -jar validator_cli.jar $GITHUB_WORKSPACE/$p -version $FHIR_VERSION $UNESCPAED_IG_DEPENDENCIES $COMBINED_IG_PARAMETERS
        done
      shell: bash
      env:
       INPUT_PATH_TO_CONFORMANCE_RESOURCES: ${{ inputs.PATH_TO_CONFORMANCE_RESOURCES }}
       PATH_TO_EXAMPLES: beispiele
       FHIR_VERSION: "4.0"
