# This is a workflow to help to update the [FHIR Java Validator](https://github.com/hapifhir/org.hl7.fhir.core) dependency automatically 

name: Update FHIR Java validator (Cron Job)

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  check-java-validator-updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq
          echo "~/bin" >> $GITHUB_PATH

      - name: Extract with default version of Java validator
        run: |
          JAVA_VALIDATOR_VERSION=$(yq '.inputs.JAVA_VALIDATOR_VERSION.default' action.yml)
          echo "JAVA_VALIDATOR_VERSION: $JAVA_VALIDATOR_VERSION"
